- type: job
  id: Gladiator
  name: job-name-gladiator
  description: job-description-gladiator
  playTimeTracker: JobPrisoner
  startingGear: GladiatorGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "Gladiator"
  supervisors: job-supervisors-security
  setPreference: false
  whitelistRequired: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600

- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: UniformShortsRed
    outerClothing: ClothingOuterArmorGladiator
    id: GladiatorPDA
    ears: ClothingHeadsetGrey
  innerclothingskirt: UniformShortsRedWithTop
  #any other possessions, spawn in cell
