- type: job
  id: MartialArtist
  name: job-name-martialartist
  description: job-description-martialartist
  playTimeTracker: JobBoxer
  startingGear: MartialGear
  icon: "MartialArtist"
  supervisors: job-supervisors-hop
  whitelistRequired: true
  access:
  - Service
  extendedAccess:
  - Maintenance

- type: startingGear
  id: MartialGear
  equipment:
    jumpsuit: ClothingUniformMartialGi
    belt: ClothingBeltMartialBlack
    back: ClothingBackpackFilled
    id: MartialArtistPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesWizard
    gloves: ClothingHandsGlovesBoxingRed
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
